/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockBlockHistory: typeof import('./components/block/BlockHistory.vue')['default']
    BlockBlockHistoryItem: typeof import('./components/block/BlockHistoryItem.vue')['default']
    BlockBlockStatistic: typeof import('./components/block/BlockStatistic.vue')['default']
    BlockBlockStats: typeof import('./components/block/BlockStats.vue')['default']
    BlockNotificationConfigForm: typeof import('./components/block/NotificationConfigForm.vue')['default']
    CharacterAtomsAvatarSearchAutocomplete: typeof import('./components/character/atoms/AvatarSearchAutocomplete.vue')['default']
    CharacterAtomsAvatarSelectionCard: typeof import('./components/character/atoms/AvatarSelectionCard.vue')['default']
    CharacterAtomsElementIcon: typeof import('./components/character/atoms/ElementIcon.vue')['default']
    CharacterAtomsEquipTag: typeof import('./components/character/atoms/EquipTag.vue')['default']
    CharacterAtomsGradeBar: typeof import('./components/character/atoms/GradeBar.vue')['default']
    CharacterAtomsGradeFrame: typeof import('./components/character/atoms/GradeFrame.vue')['default']
    CharacterAtomsItemCount: typeof import('./components/character/atoms/ItemCount.vue')['default']
    CharacterAtomsItemImage: typeof import('./components/character/atoms/ItemImage.vue')['default']
    CharacterAtomsItemLevel: typeof import('./components/character/atoms/ItemLevel.vue')['default']
    CharacterAtomsStarIcon: typeof import('./components/character/atoms/StarIcon.vue')['default']
    CharacterAtomsStatIcon: typeof import('./components/character/atoms/StatIcon.vue')['default']
    CharacterAtomsStatRow: typeof import('./components/character/atoms/StatRow.vue')['default']
    CharacterAtomsItemIcon: typeof import('./components/character/atoms/ItemIcon.vue')['default']
    CharacterMoleculesItemNameDisplay: typeof import('./components/character/molecules/ItemNameDisplay.vue')['default']
    CharacterMoleculesItemTooltip: typeof import('./components/character/molecules/ItemTooltip.vue')['default']
    CharacterMoleculesLoginInputGroup: typeof import('./components/character/molecules/LoginInputGroup.vue')['default']
    CharacterMoleculesLoginModeSelector: typeof import('./components/character/molecules/LoginModeSelector.vue')['default']
    CharacterMoleculesSkillList: typeof import('./components/character/molecules/SkillList.vue')['default']
    CharacterMoleculesStarSystem: typeof import('./components/character/molecules/StarSystem.vue')['default']
    CharacterMoleculesStatList: typeof import('./components/character/molecules/StatList.vue')['default']
    CharacterMoleculesTooltipHeader: typeof import('./components/character/molecules/TooltipHeader.vue')['default']
    CharacterOrganismsAvatarDataTable: typeof import('./components/character/organisms/AvatarDataTable.vue')['default']
    CharacterOrganismsEquipmentTable: typeof import('./components/character/organisms/EquipmentTable.vue')['default']
    CharacterOrganismsEquippedSlotsDisplay: typeof import('./components/character/organisms/EquippedSlotsDisplay.vue')['default']
    CharacterOrganismsMaterialTable: typeof import('./components/character/organisms/MaterialTable.vue')['default']
    CharacterOrganismsRuneTable: typeof import('./components/character/organisms/RuneTable.vue')['default']
    CsvCsvDataTable: typeof import('./components/csv/CsvDataTable.vue')['default']
    LayoutAppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    LayoutAppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    LayoutNotificationListener: typeof import('./components/layout/NotificationListener.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    PlanetPlanetSelector: typeof import('./components/planet/PlanetSelector.vue')['default']
    PlanetRawDataDebug: typeof import('./components/planet/RawDataDebug.vue')['default']
    PlanetRpcSettingsCard: typeof import('./components/planet/RpcSettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsApiUrlSelector: typeof import('./components/settings/ApiUrlSelector.vue')['default']
  }
}
