/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockBlockHistory: typeof import('./components/block/BlockHistory.vue')['default']
    BlockBlockHistoryItem: typeof import('./components/block/BlockHistoryItem.vue')['default']
    BlockBlockStatistic: typeof import('./components/block/BlockStatistic.vue')['default']
    BlockBlockStats: typeof import('./components/block/BlockStats.vue')['default']
    BlockNotificationConfigForm: typeof import('./components/block/NotificationConfigForm.vue')['default']
    CharacterAvatarDataTable: typeof import('./components/character/AvatarDataTable.vue')['default']
    CsvCsvDataTable: typeof import('./components/csv/CsvDataTable.vue')['default']
    LayoutAppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    LayoutAppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    LayoutNotificationListener: typeof import('./components/layout/NotificationListener.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    PlanetPlanetSelector: typeof import('./components/planet/PlanetSelector.vue')['default']
    PlanetRawDataDebug: typeof import('./components/planet/RawDataDebug.vue')['default']
    PlanetRpcSettingsCard: typeof import('./components/planet/RpcSettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsApiUrlSelector: typeof import('./components/settings/ApiUrlSelector.vue')['default']
  }
}
