/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockBlockHistory: typeof import('./components/block/BlockHistory.vue')['default']
    BlockBlockHistoryItem: typeof import('./components/block/BlockHistoryItem.vue')['default']
    BlockBlockStatistic: typeof import('./components/block/BlockStatistic.vue')['default']
    BlockBlockStats: typeof import('./components/block/BlockStats.vue')['default']
    BlockNotificationConfigForm: typeof import('./components/block/NotificationConfigForm.vue')['default']
    LayoutAppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    LayoutAppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH1: typeof import('naive-ui')['NH1']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PlanetPlanetSelector: typeof import('./components/planet/PlanetSelector.vue')['default']
    PlanetRawDataDebug: typeof import('./components/planet/RawDataDebug.vue')['default']
    PlanetRpcSettingsCard: typeof import('./components/planet/RpcSettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
